<a href="https://colab.research.google.com/github/Hoangthang017/CS112.L11/blob/master/do_an_cuoi_ky/Dijkstra_time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**cài đặt thư viện networkx để tạo đồ thị**

In [42]:
!pip install networkx

**import các thư viện cần dùng**

In [43]:
import networkx, random
import numpy as np
import cProfile
import sys

**hàm tạo đồ list đồ thị có hướng để chạy test**

In [44]:
# hàm tạo đồ thị
def create_Graphs(list_Graph,start_node = 10, probabilityOfEdges = 0.3 ,numberOfGraph = 50, rangeOfCost = 100):
  # số đỉnh ít nhất của một đồ thị
  n = start_node

  # in kiểm tra số đỉnh đang được tạo
  # print(n)

  # không có cạnh giữa 2 đỉnh
  M = float('inf')

  # hàm tạo list numberOfGraph đồ thị
  for i in range(numberOfGraph):

    # mỗi lần chạy tăng 1% số đỉnh so với lần trước
    n = int(n + n*0.1)
    # n += 1

    edges = random.random()
    while (edges < probabilityOfEdges):
      edges = random.random()
      # print(edges)

    # hàm tạo đồ thị có hướng với số cạnh được tạo ra ngẫu nhiên
    G = networkx.binomial_graph(n, edges)

    # chuyển từ dạng đồ thị sang dạng matrix 
    adjMatrix = networkx.convert_matrix.to_numpy_matrix(G)

    # hàm giá trị cạnh cho đồ thị
    for v in range(n):
      for u in range(n):
        # trùng đỉnh vẫn giữ giá trị 0
        if (v == u):
          pass 
        # có cạnh giữa 2 đỉnh gán giá trị ngẫu nhiên trong khoảng [- rangeOfCost, rangeOfCost]
        elif (adjMatrix[v,u] == 1):
          adjMatrix[v,u] = random.randint(1,rangeOfCost)
        # không có cạnh giữa 2 đỉnh
        else:
          adjMatrix[v,u] = M

    list_Graph.append(adjMatrix)

  return list_Graph
  

**các hàm của thuật toán Dijkstra**

In [45]:
# hàm lấy đường đi từ đỉnh gốc
def printSolution(V,S,dist):
  print("khoảng cách từ đỉnh ",S," đến đỉnh: ")
  for node in range(V):
    if (node != S):
      print(node, ":", dist[node])

In [49]:
# thuật toán Dijkstra
def dijkstra(graph, V, S):
  # khởi tạo các biến
  dist = [float('inf')] * V
  dist[S] = 0
  sptSet = [False] * V

  for cout in range(V):
    min = sys.maxsize
    # chọn đỉnh có đường đi ngắn nhất từ đỉnh nguồm
    # u luôn bằng đỉnh nguồn ở lần chạy đầu tiên
    u = S;
    for v in range(V):
      if dist[v] < min and sptSet[v] == False:
        min = dist[v]
        u = v  
    # cập nhật đỉnh u vào cây đường dẫn ngắn nhất
    sptSet[u] = True
 
    # chỉ cập nhật giá trị của những đỉnh liền kề với đỉnh đã chọn nếu khoảng cách hiện tại lớn hơn khoảng cách
    # mới và đỉnh không nằm trong cây đường dẫn ngắn nhất
    for v in range(V):
      if graph[u,v] > 0 and sptSet[v] == False and dist[v] > dist[u] + graph[u,v]:
        dist[v] = dist[u] + graph[u,v]
 
  # in đường đi từ đỉnh nguồn tới các đỉnh còn lại
  # printSolution(V,S,dist)
  return dist

In [47]:
# tìm tất cả cặp đường đi ngắn nhất với Dijkstra
def All_pair_Dijkstra(graph):
  dist = []
  for v in range(len(graph)):
    d = dijkstra(graph,len(graph),v)
    dist.append(d)
  print("dist\n",dist)

**hàm chính**

In [50]:
if __name__ == '__main__':
  # tạo list đồ thị
  list_Graph = []
  list_Graph = create_Graphs(list_Graph,numberOfGraph=5,start_node=4)

  for graph in list_Graph:
    print("graph\n",graph)
    All_pair_Dijkstra(graph)
    print('\n\n')

    
  # for graph in list_Graph:
  #   cProfile.run('floydWarshall(graph,len(graph))')

  # dataSize = []
  # for graph in list_Graph:
  #   dist, path = floydWarshall(graph,len(graph))
  #   size = dist.__sizeof__()
  #   dataSize.append(len(graph),size)

graph
 [[ 0. inf 39. 60.]
 [inf  0. inf inf]
 [39. inf  0. inf]
 [16. inf inf  0.]]
dist
 [[0, inf, 39.0, 60.0], [inf, 0, inf, inf], [39.0, inf, 0, 99.0], [16.0, inf, 55.0, 0]]



graph
 [[ 0. 19. 31. 57.]
 [31.  0. inf 85.]
 [ 4. inf  0. inf]
 [26. 27. inf  0.]]
dist
 [[0, 19.0, 31.0, 57.0], [31.0, 0, 62.0, 85.0], [4.0, 23.0, 0, 61.0], [26.0, 27.0, 57.0, 0]]



graph
 [[ 0. inf 89. inf]
 [inf  0. 80. 54.]
 [46. 52.  0. 89.]
 [inf 55. 67.  0.]]
dist
 [[0, 141.0, 89.0, 178.0], [126.0, 0, 80.0, 54.0], [46.0, 52.0, 0, 89.0], [113.0, 55.0, 67.0, 0]]



graph
 [[ 0. 92. inf  7.]
 [67.  0. inf inf]
 [inf inf  0. inf]
 [50. inf inf  0.]]
dist
 [[0, 92.0, inf, 7.0], [67.0, 0, inf, 74.0], [inf, inf, 0, inf], [50.0, 142.0, inf, 0]]



graph
 [[ 0.  4. 75. 99.]
 [92.  0. 65. 75.]
 [27.  8.  0. 22.]
 [47. 90. 98.  0.]]
dist
 [[0, 4.0, 69.0, 79.0], [92.0, 0, 65.0, 75.0], [27.0, 8.0, 0, 22.0], [47.0, 51.0, 98.0, 0]]



